anketing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name='login.html'), name='default_login'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('redirect/', views.role_based_redirect, name='role_based_redirect'),
    path('moderator/', views.moderator_dashboard, name='moderator_dashboard'),
    path('moderator/general-info/', views.edit_general_info, name='edit_general_info'),
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('survey/<int:survey_id>/', views.view_survey, name='view_survey'),
    path('survey/', views.fill_survey, name='fill_survey'),
    path('edit_survey/', views.edit_survey, name='edit_survey'),
    path('edit_survey/<int:survey_id>/', views.edit_survey, name='edit_survey'),

]

website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class CompanyProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='company_profile')
    email_for_newsletters = models.EmailField(verbose_name="Email для рассылки новостей HR2K")
    company_name_full = models.CharField(max_length=255, verbose_name="Название компании (полное)")
    company_name_short = models.CharField(max_length=20, verbose_name="Название компании (краткое)")
    company_logo = models.ImageField(upload_to='company_logos/', verbose_name="Логотип компании")
    postal_code = models.CharField(max_length=10, verbose_name="Почтовый индекс")
    postal_address = models.CharField(max_length=255,verbose_name="Почтовый адрес")
    responsible_email = models.EmailField(verbose_name="Email ответственного")
    responsible_name = models.CharField(max_length=255, verbose_name="Имя и фамилия ответственного")
    responsible_phone = models.CharField(max_length=30, verbose_name="Телефон ответственного")
    consent_data_processing = models.BooleanField(default=False, verbose_name="Согласие на обработку данных")
    confirmation = models.BooleanField(default=False, verbose_name="Подтверждение условий")

    def __str__(self):
        return self.company_name_full
    
class GeneralInfo(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    period = models.CharField(max_length=255, verbose_name="Период")
    main_page_content = models.TextField(verbose_name="Главная страница")
    
    methodology_file = models.FileField(upload_to='general_info/', verbose_name="Методология", blank=True, null=True)
    charter_file = models.FileField(upload_to='general_info/', verbose_name="Уставные документы", blank=True, null=True)
    results_file = models.FileField(upload_to='general_info/', verbose_name="Результаты старых рейтингов", blank=True, null=True)

    def __str__(self):
        return self.title
    

class UserMessage(models.Model):
    name = models.CharField(max_length=255, verbose_name="Имя пользователя")
    email = models.EmailField(verbose_name="Email пользователя")
    message = models.TextField(verbose_name="Сообщение")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки")

    def __str__(self):
        return f"Сообщение от {self.name} ({self.email})"
    

class CompanySurvey(models.Model):
    GEOGRAPHY_CHOICES = [
        ('federal', 'Федеральный уровень'),
        ('regional', 'Региональный уровень'),
    ]
    SPECIALIZATION_CHOICES = [
        ('full cycle', 'Агентство полного цикла'),
        ('service', 'Маркетинговые коммуникации / Маркетинговые услуги'),
        ('explore', 'Коммуникационные исследования и аналитика / Исследования и аналитика'),
        ('commune',
         'Корпоративные и общественные коммуникации, связи с общественностью и органами публичной власти / Связи с общественностью'),
        ('consult', 'Политические коммуникации / Политическое консультирование'),
        ('ads', 'Рекламные коммуникации / Реклама'),
        ('event', 'Событийные коммуникации / Мероприятия / Event'),
        ('digital', 'Цифровые коммуникации / Digital'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='surveys',blank=True, null=True)
    company_name = models.CharField(max_length=255, verbose_name="Фирменное наименование",blank=True,null=True)
    company_address = models.CharField(max_length=255,verbose_name="Адрес головного офиса",blank=True,null=True)
    specialization = models.CharField(choices=SPECIALIZATION_CHOICES, max_length=255, verbose_name="Основная специализация",blank=True,null=True)
    revenue = models.DecimalField(max_digits=12, decimal_places=2, verbose_name="Совокупная выручка", null=True, blank=True)
    geography_activity = models.CharField(
        max_length=20,
        choices=GEOGRAPHY_CHOICES,
        default='federal',
        verbose_name="География активности",
        null=True,blank=True
    )
    company_age = models.PositiveIntegerField(
        verbose_name="Возраст компании (лет)",
        null=True,
        blank=True
    )
    num_expert_employees = models.PositiveIntegerField(
        verbose_name="Количество сотрудников-экспертов",
        null=True,
        blank=True
    )
    num_employees_over_3_years = models.PositiveIntegerField(
        verbose_name="Количество сотрудников, работающих более 3 лет",
        null=True,
        blank=True
    )
    num_employees_in_communications = models.PositiveIntegerField(
        verbose_name="Количество сотрудников, работающих в коммуникациях более 3 лет",
        null=True,
        blank=True
    )
    num_government_awards = models.PositiveIntegerField(
        verbose_name="Количество государственных наград",
        null=True,
        blank=True
    )
    num_certificates = models.PositiveIntegerField(
        verbose_name="Количество сертификатов",
        null=True,
        blank=True
    )
    submission_date = models.DateField(auto_now_add=True, verbose_name="Дата заполнения")
    user_comment = models.TextField(
        verbose_name="Комментарий пользователя",
        null=True,
        blank=True
    )
    moderator_comment = models.TextField(
        verbose_name="Комментарий модератора",
        null=True,
        blank=True
    )

    survey_file = models.FileField(upload_to='survey_docs/', null=True, blank=True, verbose_name="File")
    doc = models.FileField(upload_to='survey_docs/', null=True, blank=True, verbose_name="Заверенный документ")
    logo = models.FileField(upload_to='survey_docs/', null=True, blank=True, verbose_name="Логотип")
    def __str__(self):
        return f"Анкета {self.company_name} - {self.submission_date}"
    
    
class CompanyPositioning(models.Model):
    SERVICE_CHOICES = [
        ('full cycle', 'Агентство полного цикла'),
        ('service', 'Маркетинговые коммуникации / Маркетинговые услуги'),
        ('explore', 'Коммуникационные исследования и аналитика / Исследования и аналитика'),
        ('commune',
         'Корпоративные и общественные коммуникации, связи с общественностью и органами публичной власти / Связи с общественностью'),
        ('consult', 'Политические коммуникации / Политическое консультирование'),
        ('ads', 'Рекламные коммуникации / Реклама'),
        ('event', 'Событийные коммуникации / Мероприятия / Event'),
        ('digital', 'Цифровые коммуникации / Digital'),
    ]
    survey = models.ForeignKey(CompanySurvey, on_delete=models.CASCADE, related_name='positionings')
    service = models.CharField(max_length=255, choices=SERVICE_CHOICES, default='full cycle', verbose_name="Позиционирование",null=True,blank=True)
    revenue_share = models.PositiveIntegerField(verbose_name="Распределение выручки (%)",null=True,blank=True)

class CompanyEmployees(models.Model):
    survey = models.ForeignKey(CompanySurvey, on_delete=models.CASCADE, related_name='employees')
    department = models.CharField(max_length=255, verbose_name="Название компании/отдела",null=True,blank=True)
    employee_count = models.PositiveIntegerField(verbose_name="Количество сотрудников",null=True,blank=True)

class CompanyAwards(models.Model):
    survey = models.ForeignKey(CompanySurvey, on_delete=models.CASCADE, related_name='awards')
    award_name = models.CharField(max_length=255, verbose_name="Название премии",null=True,blank=True)
    award_category = models.CharField(max_length=50, verbose_name="Категория премии",null=True,blank=True)
    award_type = models.CharField(max_length=50, verbose_name="Тип награды",null=True,blank=True)


class CompanyRevenue(models.Model):
    survey = models.ForeignKey(
        'CompanySurvey', 
        on_delete=models.CASCADE,
        related_name='revenues',
        verbose_name="Анкета"
        ,null=True,blank=True
    )
    company_name = models.CharField(
        max_length=255,
        verbose_name="Название компании",null=True,blank=True
    )
    inn = models.CharField(
        max_length=12,
        verbose_name="ИНН компании",null=True,blank=True
    )
    ownership_share = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        verbose_name="Доля владения (%)",null=True,blank=True
    )
    buying_share = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        verbose_name="Доля баинга в выручке (%)",null=True,blank=True
    )
    revenue_amount = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        verbose_name="Доля выручки (тыс. рублей)",null=True,blank=True
    )

    def __str__(self):
        return f"{self.company_name} (ИНН: {self.inn}) - Выручка: {self.revenue_amount} тыс. руб."

    def calculate_total_revenue_for_survey(self):
        """
        Считает общую выручку для всех объектов CompanyRevenue,
        привязанных к указанной анкете.
        """
        total_revenue = CompanyRevenue.objects.filter(survey=self.survey).aggregate(
            total=Sum('revenue_amount')
        )['total']
        return total_revenue or 0

class CompanyEvent(models.Model):
    EVENT_FORMAT_CHOICES = [
        ('online', 'Онлайн'),
        ('offline', 'Оффлайн'),
        # ('hybrid', 'Гибридный'),
    ]

    PARTICIPATION_TYPE_CHOICES = [
        # ('speaker', 'Спикер'),
        # ('participant', 'Участник'),
        ('organizer', 'Организатор'),
        ('sooorganizer', 'Со-организатор'),
    ]
    EVENT_TYPE_CHOICES = [('solo', 'Единичное'), ('complex', 'Комплексная программа')]
    AUDIENCE_TYPE_CHOICES = [('students', 'Студенты'), ('prof', 'Проф. Сообщества')]
    survey = models.ForeignKey(
        'CompanySurvey',
        on_delete=models.CASCADE,
        related_name='events',
        verbose_name="Анкета"
    )
    event_name = models.CharField(max_length=255, verbose_name="Название мероприятия", null=True, blank=True)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Моя страница{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/other/vars.css' %}" />
    <link rel="stylesheet" href="{% static 'css/other/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/other/fonts.css' %}" />
    <link rel="stylesheet" href="{% static 'css/components/components.css' %}" />
    <link rel="stylesheet" href="{% static 'css/components/header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/components/footer.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <!-- Верхняя панель -->
    <div class="top-bar">
      <div class="top-bar-content">
        <div class="logo">
          <img src="{% static 'images/logo.png' %}" alt="НР 2К" />
          <b class="logo-title">Регистрация</b>
        </div>
        <div class="title">
          XII НАЦИОНАЛЬНЫЙ РЕЙТИНГ КОММУНИКАЦИОННЫХ КОМПАНИЙ<br />
          АНКЕТА 2025 (за 2024 год)
        </div>
      </div>
    </div>

    <!-- Основное содержимое -->
    <div class="container">
      {% block content %}
      <!-- Содержимое страницы -->
      {% endblock %}
    </div>

    <footer class="footer">
        <div class="footer-text">© 2025. НР2К</div>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/edit_survey.html
{% extends "base.html" %}
{% block title %}Редактировать анкету{% endblock %}
{% block content %}
{% load static %}
<script>
        
    function addRow(sectionId, prefix) {
        const section = document.getElementById(sectionId);
        const totalForms = document.getElementById('id_form-TOTAL_FORMS');
        const currentIndex = parseInt(totalForms.value); 
        const newRow = section.lastElementChild.cloneNode(true);

                const inputs = newRow.querySelectorAll('input, select, textarea'); 
                inputs.forEach(input => {
                    if (input.name) {
                        input.name = input.name.replace(/-\d+-/, `-${currentIndex}-`);
                    }
                    if (input.id) {
                        input.id = input.id.replace(/-\d+-/, `-${currentIndex}-`); 
                    }
                    input.value = '';
                });

                section.appendChild(newRow);
                totalForms.value = currentIndex + 1;
            }

    document.addEventListener('DOMContentLoaded', function () {
const form = document.querySelector('form');
if (form) {
    form.addEventListener('submit', function(event) {
        console.log('Форма готова к отправке');
    });
} else {
    console.error('Форма не найдена');
}
});
</script>
<link rel="stylesheet" href="{% static 'registration.css' %}">
<div class="container">
    <h1>Редактировать анкету</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ formset.management_form }}
        {{ positioning_formset.management_form }}
        {{ employees_formset.management_form }}
        {{ awards_formset.management_form }}
        {{ events_formset.management_form }}
        {{ revenue_formset.management_form }}

        <div class="form-group">
            <label for="{{ survey_form.company_name.id_for_label }}">1. Фирменное название компании</label>
            {{ survey_form.company_name }}
        </div>
        <div class="form-group">
            <label for="{{ survey_form.company_address.id_for_label }}">2. Адрес головного офиса</label>
            {{ survey_form.company_address }}
        </div>
        <div class="form-group">
            <label for="{{ survey_form.specialization.id_for_label }}">3. Основная специализация компании</label>
            {{ survey_form.specialization }}
        </div>

        <div class="form-group">
            <label>4. Приоритетное позиционирование компании</label>
            <div id="positioning-section" class="dynamic-section">
                <div class="row">
                    {% for form in positioning_formset %}
                    {{ form }}
                    {% endfor %}
                </div>
            </div>
            <button type="button" onclick="addRow('positioning-section')">Добавить строку</button>
        </div>

        <div class="form-group">
            <label>5. География активности</label>
            {{ survey_form.geography_activity }}
        </div>

        <div class="form-group">
            <label>6. Совокупная выручка</label>
            <div id="revenue-section" class="dynamic-section">
                <div class="row">
                    {% for form in revenue_formset %}
                    {{ form }}
                    {% endfor %}
                </div>
            </div>
            <button type="button" onclick="addRow('revenue-section')">Добавить строку</button>
        </div>

        <div class="form-group">
            <label>7. Количество сотрудников</label>
            <div id="employees-section" class="dynamic-section">
                <div class="row">
                    {% for form in employees_formset %}
                    {{ form }}
                    {% endfor %}
                </div>
            </div>
            <button type="button" onclick="addRow('employees-section')">Добавить строку</button>
        </div>

        <div class="form-group">
            <label>8. Возраст компании</label>
            {{ survey_form.company_age }}
        </div>

        <div class="form-group">
            <label>9. Премии</label>
            <div id="awards-section" class="dynamic-section">
                <div class="row">
                    {% for form in awards_formset %}
                    {{ form }}
                    {% endfor %}
                </div>
            </div>
            <button type="button" onclick="addRow('awards-section')">Добавить строку</button>
        </div>

        <div class="form-group">
            <label>10. Профессиональные мероприятия</label>
            <div id="events-section" class="dynamic-section">
                <div class="row">
                    {% for form in events_formset %}
                    {{ form }}
                    {% endfor %}
                </div>
            </div>
            <button type="button" onclick="addRow('events-section')">Добавить строку</button>
        </div>

        <div class="form-group">
            <label>Комментарий</label>
            {{ survey_form.user_comment }}
        </div>
        <div class="form-group">
            <label>Комментарий модератора</label>
            <span readonly>{{ moderator_comment }}</span>
        </div>

        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
    </form>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Заполнение анкеты{% endblock %}
{%block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/pages/login.css' %}" />
<div class="login-page">
  <div class="login-text">
    <p class="login-text__item inter-m text-primary">
      Анкету необходимо предоставить до: 26 апреля 2025 года.
    </p>
    <p class="login-text__item inter-m text-primary">
      Анкету необходимо заверить подписью ответственного лица и печатью
      организации.
    </p>
    <p class="login-text__item inter-m text-primary">
      Материалы предоставляются в версии pdf (заверенная версия).
    </p>
    <p class="login-text__item inter-m text-primary">Заверяется только первый лист анкеты.</p>
    <p class="login-text__item inter-m text-primary">
      По всем вопросам, связанным с участием в рейтинге и/или заполнением
      анкеты, пишите на profiles@nr2c.ru.
    </p>
  </div>
  <div class="login-form">
    <form method="post" action="{% url 'login' %}">
      {% csrf_token %}
      <input class="login-input" type="text" name="username" placeholder="Логин" required /><br />
      <input
        class="login-input"
        type="password"
        name="password"
        placeholder="Пароль"
        required
      />
      <button class="login-btn" type="submit">Вход</button>
    </form>
  </div>
  <a class="login-link link-primary inter-m" href="{% url 'register' %}">Регистрация</a>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}
{%block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/pages/registration.css' %}">

<form class="register-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="{{ user_form.username.id_for_label }}">Логин (email)</label>
        {{ user_form.username }}
    </div>
    <div class="form-group">
        <label for="{{ user_form.password.id_for_label }}">Пароль</label>
        {{ user_form.password }}
    </div>
    <div class="form-group">
        <label for="{{ user_form.confirm_password.id_for_label }}">Повторите пароль</label>
        {{ user_form.confirm_password }}
    </div>

    <div class="form-group">
        <label for="{{ company_form.email_for_newsletters.id_for_label }}">Email для новостей/рассылок НР2К</label>
        {{ company_form.email_for_newsletters }}
    </div>
    <div class="form-group">
        <label for="{{ company_form.company_name_full.id_for_label }}">Название компании (полное)</label>
        {{ company_form.company_name_full }}
    </div>
    <div class="form-group">
        <label for="{{ company_form.company_name_short.id_for_label }}">Название компании (краткое, до 20 символов)</label>
        {{ company_form.company_name_short }}
    </div>
    <div class="form-group register-img">
        <label>Логотип компании (png или svg)</label>
        <img class="register-img__img" width="25%" height="25%" alt="Company Logo" style="display: none;">

        {{ company_form.company_logo }}
        <div class="register-img__body">
            <button type="button" class="register-img__btn btn-primary">Загрузить файл</button>
            <div class="register-img__text">
                <span class="register-img__text-title"></span>
                <button type="button" class="register-img__btn--delete hidden">
                    <img src="{% static 'images/chrest.svg' %}" alt="delete img">
                </button>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="{{ company_form.postal_code.id_for_label }}">Почтовый индекс</label>
        {{ company_form.postal_code }}
    </div>
    <div class="form-group">
        <label for="{{ company_form.postal_address.id_for_label }}">Почтовый адрес (для корреспонденции)</label>
        {{ company_form.postal_address }}
    </div>
    <div class="form-group">
        <label for="{{ company_form.responsible_email.id_for_label }}">Email ответственного</label>
        {{ company_form.responsible_email }}
    </div>
    <div class="form-group">
        <label for="{{ company_form.responsible_name.id_for_label }}">Имя и фамилия ответственного</label>
        {{ company_form.responsible_name }}
    </div>
    <div class="form-group">
        <label for="{{ company_form.responsible_phone.id_for_label }}">Телефон ответственного</label>
        {{ company_form.responsible_phone }}
    </div>
    <div class="confirmation-container">
        <div class="checkbox-container">
            <div class="checkbox-container__item">
                <input type="checkbox" id="id_consent_data_processing" name="id_consent_data_processing" required>
                <label class="checkbox-label" for="{{ company_form.consent_data_processing.id_for_label }}">Согласие на обработку данных и получение рассылки</label>
            </div>
            <div class="checkbox-container__item">
                <input type="checkbox" id="id_confirmation" name="id_confirmation" required>
                <label class="checkbox-label" for="{{ company_form.confirmation.id_for_label }}">Я подтверждаю:</label>
            </div>
        </div>
        <ul class="confirmation-list">
            <li>Бренд компании-участника существует на рынке более 3-х лет.</li>
            <li>Компания-участник предоставляет услуги, включённые в Классификатор коммуникационных индустрий, утверждённый Координационным советом коммуникационной индустрии при Общественной палате РФ, за исключением услуг по медиаразмещению.</li>
            <li>Учредителем (участником) компании или аффилированным лицом компании не является орган публичной власти, государственное, муниципальное учреждение, государственная корпорация и иное юридическое лицо с государственным участием.</li>
            <li>Предоставляя свои данные, агентство подтверждает согласие со структурой и методологией рейтингов, выражает доверие его организаторам, операторам и экспертному совету.</li>
        </ul>
    </div>

    <button class="register-btn" type="submit">Зарегистрироваться</button>
</form>
{% endblock %}

templates/view_survey.html
{% extends "base.html" %}
{% block title %}Редактировать анкету{% endblock %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'registration.css' %}">
<div class="container">

        <div class="form-group">
            <label>1. Фирменное название компании</label>
            {{ survey.company_name }}
        </div>
        <div class="form-group">
            <label for="{{ survey_form.company_address.id_for_label }}">2. Адрес головного офиса</label>
            {{ survey.company_address }}
        </div>
        <div class="form-group">
            <label for="{{ survey_form.specialization.id_for_label }}">3. Основная специализация компании</label>
            {{ survey.specialization }}
        </div>

        <div class="form-group">
            <label>4. Приоритетное позиционирование компании</label>
            <div id="positioning-section" class="dynamic-section">
                <div class="row">
                    {% for positioning in positionings %}
                
                    {{ positioning.service }}
                    {{ positioning.revenue_share }}
                
                {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group">
            <label>5. География активности</label>
            {{ survey.geography_activity }}
        </div>

        <div class="form-group">
            <label>6. Совокупная выручка</label>
            <div id="revenue-section" class="dynamic-section">
                <table>
                    <thead>
                        <tr>
                            <th>Название компании</th>
                            <th>ИНН</th>
                            <th>Доля владения (%)</th>
                            <th>Доля баинга (%)</th>
                            <th>Выручка (тыс. рублей)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for revenue in revenues %}
                        <tr>
                            <td>{{ revenue.company_name }}</td>
                            <td>{{ revenue.inn }}</td>
                            <td>{{ revenue.ownership_share }}</td>
                            <td>{{ revenue.buying_share }}</td>
                            <td>{{ revenue.amount }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="form-group">
            <label>7. Количество сотрудников</label>
            <div id="employees-section" class="dynamic-section">
                <table>
                    <thead>
                        <tr>
                            <th>Компания/Отдел</th>
                            <th>Количество сотрудников</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in employees %}
                        <tr>
                            <td>{{ employee.department }}</td>
                            <td>{{ employee.employee_count }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>        </div>

        <div class="form-group">
            <label>8. Возраст компании</label>
            {{ survey.company_age }}
        </div>

        <div class="form-group">
            <label>9. Премии</label>
            <div id="awards-section" class="dynamic-section">
                <table>
                    <thead>
                        <tr>
                            <th>Название</th>
                            <th>Категория</th>
                            <th>Тип награды</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for award in awards %}
                        <tr>
                            <td>{{ award.award_name }}</td>
                            <td>{{ award.award_category }}</td>
                            <td>{{ award.award_type }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="form-group">
            <label>10. Профессиональные мероприятия</label>
            <div id="events-section" class="dynamic-section">
                <table>
                    <thead>
                        <tr>
                            <th>Количество</th>
                            <th>Аудитория</th>
                            <th>Участники</th>
                            <th>Формат</th>
                            <th>Тип мероприятия</th>
                            <th>Тип участия</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for event in events %}
                        <tr>
                            <td>{{ event.count }}</td>
                            <td>{{ event.audience }}</td>
                            <td>{{ event.participant_count }}</td>
                            <td>{{ event.event_format }}</td>
                            <td>{{ event.event_type }}</td>
                            <td>{{ event.participation_type }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="form-group">
            <label>Комментарий</label>
            {{ survey.user_comment }}
        </div>
    </form>
</div>
{% endblock %}